# Site settings
title: Kerst_ker
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kerst_ker
user_description: 一位绘画的代码人
user_title: NOPE
email: kerstsama@gmail.com
# twitter_username: lorem_ipsum
instagram_username: kerst_ker
facebook_username: kerst_ker
linkedin_username: kerst_ker
github_username:  kerst_ker
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
